version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
      - redis
    environment:
      - ASPNETCORE_URLS=http://*:5000
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_mysql_root_password
      - MYSQL_DATABASE=your_database_name
      - MYSQL_USER=your_mysql_username
      - MYSQL_PASSWORD=your_mysql_password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  mysql_data:
  redis_data:

