# role-binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: firstrole
  namespace:  mycluster
subjects:
- kind: ServiceAccount
  name: bhupati
  namespace:  mycluster
roleRef:
  kind: Role # or ClusterRole for a ClusterRole
  name: firstrole
  apiGroup: rbac.authorization.k8s.io